Repository aragon/aragon-apps, pull requests merged in 2018-06, with the labels that each got.

#357 Update test-helpers version
  shared/test-helpers/package.json
Labels: status: quick-review-and-merge

#310 Survey app
  apps/survey/app/.babelrc
  apps/survey/app/.eslintrc
  apps/survey/app/.gitignore
  apps/survey/app/README.md
  apps/survey/app/index.html
  apps/survey/app/package-lock.json
  apps/survey/app/package.json
  apps/survey/app/public/images/icon.svg
  apps/survey/app/src/App.js
  apps/survey/app/src/abi/token-balanceOfAt.json
  apps/survey/app/src/abi/token-decimals.json
  apps/survey/app/src/abi/token-symbol.json
  apps/survey/app/src/components/AppBar/AppBar.js
  apps/survey/app/src/components/AppBar/LeftIcon.js
  apps/survey/app/src/components/Creator/Creator.js
  apps/survey/app/src/components/NewSurveyPanel/NewSurveyPanel.js
  apps/survey/app/src/components/Survey/Survey.js
  apps/survey/app/src/components/Survey/SurveyDetails.js
  apps/survey/app/src/components/Survey/SurveySidebar.js
  apps/survey/app/src/components/Survey/VotesCast.js
  apps/survey/app/src/components/Survey/VotesHistory.js
  apps/survey/app/src/components/SurveyCard/SurveyCard.js
  apps/survey/app/src/components/SurveyCard/SurveyCardGroup.js
  apps/survey/app/src/components/SurveyOptions/SurveyOption.js
  apps/survey/app/src/components/SurveyOptions/SurveyOptions.js
  apps/survey/app/src/components/Surveys/Surveys.js
  apps/survey/app/src/components/VotingPanel/VotingPanel.js
  apps/survey/app/src/demo-state.js
  apps/survey/app/src/index.js
  apps/survey/app/src/math-utils.js
  apps/survey/app/src/option-utils.js
  apps/survey/app/src/provide-network.js
  apps/survey/app/src/rxjs.js
  apps/survey/app/src/script.js
  apps/survey/app/src/springs.js
  apps/survey/app/src/survey-settings.js
  apps/survey/app/src/time-utils.js
  apps/survey/app/src/utils.js
  apps/survey/manifest.json
Labels: component: dapp, epic: Signaling, sprint: 0.5.1

#320 Update licenses to include both GPL and AGPL
  LICENSE
  apps/finance/app/package.json
  apps/finance/contracts/Finance.sol
  apps/finance/package.json
  apps/survey/app/package.json
  apps/survey/contracts/Survey.sol
  apps/survey/package.json
  apps/token-manager/app/package.json
  apps/token-manager/contracts/TokenManager.sol
  apps/token-manager/package.json
  apps/vault/package.json
  apps/voting/app/package.json
  apps/voting/contracts/Voting.sol
  apps/voting/package.json
  package.json
Labels: epic: aragon-apps next, sprint: 0.5.2

#377 Survey: update aragon-ui to 0.15.0
  apps/survey/app/.gitignore
  apps/survey/app/package-lock.json
  apps/survey/app/package.json
Labels: epic: in sprint addition, sprint: 0.5.2

#367 Survey fixes
  apps/survey/app/src/components/Survey/Survey.js
  apps/survey/app/src/components/Survey/SurveyDetails.js
  apps/survey/app/src/components/Survey/VotesCast.js
  apps/survey/app/src/components/Survey/VotesHistory.js
Labels: app: survey, sprint: 0.5.2
