Repository aragon/aragon-apps, pull requests merged in 2021-09, with the labels that each got.

#1321 DAO-343: reuse builder config file
  apps/agent/buidler.config.js
  apps/agreement/buidler.config.js
  apps/finance/buidler.config.js
  apps/token-manager/buidler.config.js
  apps/vault/buidler.config.js
  apps/voting-disputable/buidler.config.js
  apps/voting/buidler.config.js
  shared/buidler.config.js
Labels: app: vault, app: finance, app: voting, app: token manager, app: agent

#1320 [cicd] adds auto release workflow
  .github/release.yml
Labels: voting:patch, rinkeby, mumbai

#1323 [cicd] moves workflows into the correct folder
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: agent:patch, rinkeby, mumbai

#1324 [cicd] fixes fails in deploy and release workflows
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: agent:patch, rinkeby, mumbai

#1325 [cicd] fixes more fails in workflows
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: agent:patch, rinkeby, mumbai

#1326 [cicd] another round of fixes in release workflow
  .github/workflows/release.yml
Labels: agent:patch, rinkeby, mumbai
